version: '2.1'
services:
  api-gateway-2:
    build: .
    environment:
      PORT: '5001'
      SHOW_URLS: 'true'
      IMAGES_URL: '192.168.99.101'
      IMAGES_PORT: '3002'
      IMAGES_ENTRY: 'images'
      TYPE_IMAGES_ENTRY: 'typeimages'
      OWNER_IMAGES_ENTRY: 'ownerimages'
      TYPE_OWNER_IMAGES_ENTRY: 'typeownerimages'
    ports:
      - '5001:5001'
